### ISSUE TITLE
Use `PARSE_ARGV` in all `cmake_parse_arguments` calls

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#104]
The `PARSE_ARGV` mode of `cmake_parse_arguments` handles special characters in arguments correctly.

**Comment by cblichmann** [comment]
Note that we can only to that for `function()`s. Within a `macro()`, the regular `cmake_parse_arguments()` invocation has to be used (https://cmake.org/cmake/help/latest/command/cmake_parse_arguments.html).

**Comment by DemiMarie** [comment]
@cblichmann what are the advantages of `macro()` over `function()`?
