### ISSUE TITLE
Fails to build using clang

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#109]
<pre>[412/505] Building CXX object sandboxed-api-build/sandboxed_api/sandbox2/CMakeFiles/sandbox2_syscall.dir/syscall_defs.cc.o
<font color="#C01C28">FAILED: </font>sandboxed-api-build/sandboxed_api/sandbox2/CMakeFiles/sandbox2_syscall.dir/syscall_defs.cc.o 
/usr/bin/clang++ -DGOOGLE_GLOG_DLL_DECL=&quot;&quot; -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/absl-src -I/home/user/sandboxed-api/build/contrib/turbojpeg/sandboxed-api-build -I/home/user/sandboxed-api -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/protobuf-src/src -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/glog-build -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/glog-src/src -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/gflags-build/include -I/home/user/sandboxed-api/build/contrib/turbojpeg/_deps/gflags-build -fsanitize=address,undefined -g -fcolor-diagnostics -fno-exceptions -Wno-deprecated -Wframe-larger-than=40960 -Wno-deprecated-declarations -Wno-psabi -std=gnu++17 -MD -MT sandboxed-api-build/sandboxed_api/sandbox2/CMakeFiles/sandbox2_syscall.dir/syscall_defs.cc.o -MF sandboxed-api-build/sandboxed_api/sandbox2/CMakeFiles/sandbox2_syscall.dir/syscall_defs.cc.o.d -o sandboxed-api-build/sandboxed_api/sandbox2/CMakeFiles/sandbox2_syscall.dir/syscall_defs.cc.o -c /home/user/sandboxed-api/sandboxed_api/sandbox2/syscall_defs.cc
In file included from /home/user/sandboxed-api/sandboxed_api/sandbox2/syscall_defs.cc:1:
In file included from /home/user/sandboxed-api/sandboxed_api/sandbox2/syscall_defs.h:10:
In file included from /home/user/sandboxed-api/build/contrib/turbojpeg/_deps/absl-src/absl/strings/string_view.h:30:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/algorithm:74:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/pstl/glue_algorithm_defs.h:13:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:54:
In file included from /usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:39:
<b>/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/array:268:52: </b><font color="#C01C28"><b>fatal error: </b></font><b>instantiating fold expression with 334 arguments exceeded expression nesting limit of 256</b>
      -&gt; array&lt;enable_if_t&lt;(is_same_v&lt;_Tp, _Up&gt; &amp;&amp; ...), _Tp&gt;,
<font color="#26A269"><b>                           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~</b></font>
<b>/home/user/sandboxed-api/sandboxed_api/sandbox2/syscall_defs.cc:155:22: </b><font color="#171421"><b>note: </b></font>while substituting deduced template arguments into function template &apos;&lt;deduction guide for array&gt;&apos; [with _Tp = sandbox2::SyscallTable::Entry, _Up = &lt;sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry, sandbox2::SyscallTable::Entry&gt;]
</pre>

**Comment by cblichmann** [comment]
Which version of Clang are you using?

This looks like `-fbracket-depth` could be used to fix this (https://clang.llvm.org/docs/UsersManual.html#cmdoption-fbracket-depth). This option seems to be somewhat recent (https://reviews.llvm.org/D86936) and controversial (https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg50598.html).

**Comment by DemiMarie** [comment]
<pre>[user@sandboxed-api]~/sandboxed-api% rpm -qv clang
clang-13.0.0-3.fc35.x86_64
</pre>

**Comment by happyCoder92** [comment]
Workaround landed with 10c04ed but actually this seems like a libstdc++ deficiency - libc++ would not show the problem as it does not use a fold expression in std::array's CTAD.

**Comment by cblichmann** [comment]
Thanks @happyCoder92, closing.

I don't think we can convince libstdc++ do change their implementation for Clang here.
