### ISSUE TITLE
New generator fails to convert `_Bool` to `bool`

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#154]
C’s `_Bool` needs to be converted to C++’s `bool`.  This breaks the libzip build after some other patches have been applied to fix other errors.

**Comment by cblichmann** [comment]
There's a TODO for this: https://github.com/google/sandboxed-api/blob/main/sandboxed_api/tools/clang_generator/types.cc#L220

**Comment by DemiMarie** [comment]
I worked around it by using `typedef bool _Bool;`, though this is technically undefined behavior.
