### ISSUE TITLE
Fix for #154 doesn’t work for return values

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#158]
The fix for #154 doesn’t work for functions that return `_Bool`.  I still need a `typedef bool _Bool;` in the libzip contrib.

**Comment by cblichmann** [comment]
That's odd, I tested this with:
```c++
extern _Bool MyFunc() { return 0; }
```

The generator correctly outputs this method:
```c++
  // ...
  // _Bool MyFunc()
  ::absl::StatusOr<bool> MyFunc() {
    ::sapi::v::Bool v_ret_;

    SAPI_RETURN_IF_ERROR(sandbox_->Call("MyFunc", &v_ret_));
    return v_ret_.GetValue();
  }
  // ...
```

I also don't see _any_ reference to `_Bool` in libzip. A quick `grep -R _Bool` in libzip's source directory comes back empty.

**Comment by DemiMarie** [comment]
Looks like a stale header or something.  In any case I cannot reproduce it.

> I also don't see _any_ reference to `_Bool` in libzip. A quick `grep -R _Bool` in libzip's source directory comes back empty.

Not surprised; `<stdbool.h>` contains `#define bool _Bool`.
