### ISSUE TITLE
Updating the contributing.md file

### ISSUE THREAD

**Issue by HimanshuMahto** [google/sandboxed-api#170]
Maybe an update to CONTRIBUTING.md would be amazing.
Unlike other amazing repos, this repo's CONTRIBUTING.md looks plain and simple.

i think emojified, fun and precise version would be better!

Describe alternatives you've considered
An update would be amazing!

Additional context
If you are reading this, you are amazing! ⭐

Starred ⭐✔️

Thanks and regards,
Himanshu

**Comment by cblichmann** [comment]
Let's keep it plain and boring.
