### ISSUE TITLE
need a section which explains how to run examples illustrated

### ISSUE THREAD

**Issue by cedric05** [google/sandboxed-api#19]
new to bazel, how can i run examples

**Comment by cedric05** [comment]
i had to check entire documentation of bazel to come up with this. 
`bazel build //sandboxed_api:sapi`
i'm still unsure about how to run examples

**Comment by cedric05** [comment]
with my understandings you need following
it only works with python3.
`pip install clang` from [clang](https://github.com/ethanhs/clang)
and run
`bazel build //sandboxed_api/examples/sum:main_sum`
after running above command if you get any error stating `libclang.so` missing!!!
[follow](https://github.com/mapbox/cncc/issues/6#issuecomment-278010018)


if you are able to build without errors.
to run `bazel run //sandboxed_api/examples/sum:main_sum`

**Comment by happyCoder92** [comment]
There is a "Quick start" section in the main README.
https://github.com/google/sandboxed-api#quick-start
It also lists the required dependencies for Debian 10 Buster (other distros to be added - tracked as #16).
