### ISSUE TITLE
Reverse direction calls from sandbox to the host?

### ISSUE THREAD

**Issue by avasylev** [google/sandboxed-api#31]
SAPI provides nice abstraction for calling from the host into the sandbox. Is there a way to use same abstractions to facilitate calls in reverse direction - from sandbox into the host? 
In my case that would allow sandbox to pull optional data from the host if it needs it.

**Comment by cblichmann** [comment]
We don't have that out of the box.
You can kind of fake this, though: Have the host code call the sandboxee in a loop and interpret its return value as "I need more/this data".

Something like this (pseudo-code):
```
MyApi api(GetSandbox());
std::vector<int> data = ComputeInitialData();
int sandboxee_index = 0;
while (true) {  // TODO: Abort after timeout/number of loops to avoid DoS.
  sapi::v::LenVal chunk(data, data.size());
  SAPI_ASSIGN_OR_RETURN(sandboxee_index, api.ProcessChunk(chunk.PtrBefore()));
  if (sandboxee_index == -1) break;  // Done processing
  data = ComputeMoreData(sandboxee_index);  // Generate more data for the sandboxee
}
```
