### ISSUE TITLE
what's the main differences between docker-like container and sandbox2?

### ISSUE THREAD

**Issue by snowolfhawk** [google/sandboxed-api#41]
I feel that the sandboxed-api/sandbox2 is mainly a subset of docker-like containers, the container have more features like CRI for k8s.....

If i'am wrong, Could you explain it in detail?

**Comment by fluxchief** [comment]
What exactly do you mean by 'docker&vm'?
Docker is not a sandbox. While it uses namespaces to isolate processes somewhat, sandbox2 also applies seccomp rules restricting the application in what it can.

**Comment by cblichmann** [comment]
I assume by "docker&vm" you mean running Docker containers on a runtime that uses VMs for isolation, such as [gVisor](https://gvisor.dev/) or [Kata Containers](https://katacontainers.io/) on top of QEMU or Firecracker?

Plain Docker, running directly on the host, is usually not considered to be a security boundary. The technology behing Linux containers is namespaces and it requires a combination of different namespace entities to isolate a container from the host. Namespaces are a kernel feature that allows to present a subset of actual kernel entities to a process. In that, it is similar to `chroot()`, but more general.

Now, running Docker with a container runtime that uses VMs will boot a full kernel (not necessarily Linux) and use its drivers to map host resources into the guest. The level of isolation varies, but it will usually be hardware enforced. Starting such a container is usually slow, taking anywhere from tens of milliseconds to 100s of milliseconds.

Sandbox2, the underlying technology behind Sandboxed API uses the Linux kernel's BPF and seccomp facilites to implement security policies. It also uses namespaces to provide a different view of the hosts resources to the sandboxee, namely only the ones that the sandboxee needs. The seccomp/BPF part implements something not dissimliar to a syscall firewall, only allowing those operating system APIs to be called that are covered by the security policy. On top of that, Sandbox2 sandboxes start much quicker, usually in less than 20ms.

Using the host kernel is also a compatibility advantage: Projects like gVisor have to go to greate lengths to ensure application compatiblity, for example.

So the TL;DR is that Sandbox2 implements fine-grained security policies and is generally lighter-weight in terms of host resources. Docker+vm solutions are often easier to configure, but start slower because they have to boot a full kernel.

**Comment by snowolfhawk** [comment]
> I assume by "docker&vm" you mean running Docker containers on a runtime that uses VMs for isolation, such as [gVisor](https://gvisor.dev/) or [Kata Containers](https://katacontainers.io/) on top of QEMU or Firecracker?
> 
> Plain Docker, running directly on the host, is usually not considered to be a security boundary. The technology behing Linux containers is namespaces and it requires a combination of different namespace entities to isolate a container from the host. Namespaces are a kernel feature that allows to present a subset of actual kernel entities to a process. In that, it is similar to `chroot()`, but more general.
> 
> Now, running Docker with a container runtime that uses VMs will boot a full kernel (not necessarily Linux) and use its drivers to map host resources into the guest. The level of isolation varies, but it will usually be hardware enforced. Starting such a container is usually slow, taking anywhere from tens of milliseconds to 100s of milliseconds.
> 
> Sandbox2, the underlying technology behind Sandboxed API uses the Linux kernel's BPF and seccomp facilites to implement security policies. It also uses namespaces to provide a different view of the hosts resources to the sandboxee, namely only the ones that the sandboxee needs. The seccomp/BPF part implements something not dissimliar to a syscall firewall, only allowing those operating system APIs to be called that are covered by the security policy. On top of that, Sandbox2 sandboxes start much quicker, usually in less than 20ms.
> 
> Using the host kernel is also a compatibility advantage: Projects like gVisor have to go to greate lengths to ensure application compatiblity, for example.
> 
> So the TL;DR is that Sandbox2 implements fine-grained security policies and is generally lighter-weight in terms of host resources. Docker+vm solutions are often easier to configure, but start slower because they have to boot a full kernel.

sorry for improper compare for vm, actually i just mean docker-like containers。
The seccomp policy also used in docker:
https://docs.docker.com/engine/security/seccomp/

**Comment by snowolfhawk** [comment]
I'am interested in this project for that IOT devices need security sandbox in my work. sandbox2 only support x86 & powerpc platforms up to now, i need fix it for arm32/arm64, do you have plan for arm support?

**Comment by fluxchief** [comment]
https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
The default docker seccomp policy denies some sensitive syscalls while with sandbox2 you have
to whitelist the syscalls (up to per-argument granularity).

> do you have plan for arm support?
We're looking into this but we don't have anything concrete at this point.
If you need some namespace/seccomp based isolation maybe have a look at [nsjail](https://github.com/google/nsjail) as well (which is a stand-alone application vs a library).

> If sandbox2 support Container Runtime Interface(CRI) used by k8s，it will be a lightweight iot "docker"
@cblichmann can probably answer this better than me but I assume that this is not something we want to pursue. Sandbox2 is not intended to give a full 'container' but rather run a single application in a tight sandbox. Running additional applications in the same sandbox requires a more relaxed policy and will reduce the overall effectiveness.

**Comment by snowolfhawk** [comment]
> https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
> The default docker seccomp policy denies some sensitive syscalls while with sandbox2 you have
> to whitelist the syscalls (up to per-argument granularity).
> 
> > do you have plan for arm support?
> 
> We're looking into this but we don't have anything concrete at this point.
> If you need some namespace/seccomp based isolation maybe have a look at [nsjail](https://github.com/google/nsjail) as well (which is a stand-alone application vs a library).
> 
> > If sandbox2 support Container Runtime Interface(CRI) used by k8s，it will be a lightweight iot "docker"
> 
> @cblichmann can probably answer this better than me but I assume that this is not something we want to pursue. Sandbox2 is not intended to give a full 'container' but rather run a single application in a tight sandbox. Running additional applications in the same sandbox requires a more relaxed policy and will reduce the overall effectiveness.

Do you have any public slides or videos explained in details for sandboxed-api/sandbox2 project?
I can only find <Developer Guide>.

**Comment by cblichmann** [comment]
> > We're looking into this but we don't have anything concrete at this point.
> > If you need some namespace/seccomp based isolation maybe have a look at [nsjail](https://github.com/google/nsjail) as well (which is a stand-alone application vs a library).
> > > If sandbox2 support Container Runtime Interface(CRI) used by k8s，it will be a lightweight iot "docker"
> > 
> > 
> > @cblichmann can probably answer this better than me but I assume that this is not something we want to pursue. Sandbox2 is not intended to give a full 'container' but rather run a single application in a tight sandbox. Running additional applications in the same sandbox requires a more relaxed policy and will reduce the overall effectiveness.
> 

Precisely. We do not want to become a full container runtime. That space is already plenty crowded and has a lot of great solutions available. gVisor and Kata on the VM side and custom seccomp policies on the upstream Docker side. There are others as well.

> Do you have any public slides or videos explained in details for sandboxed-api/sandbox2 project?
> I can only find "Developer Guide".

No, there are no public slides or videos. What content would you like to see a video for? Personally, I rarely find those useful. I do agree that our documentation can be improved a lot, but I think our time is better spend on creating tutorials/codelabs and background articles.

**Comment by snowolfhawk** [comment]
> > > We're looking into this but we don't have anything concrete at this point.
> > > If you need some namespace/seccomp based isolation maybe have a look at [nsjail](https://github.com/google/nsjail) as well (which is a stand-alone application vs a library).
> > > > If sandbox2 support Container Runtime Interface(CRI) used by k8s，it will be a lightweight iot "docker"
> > > 
> > > 
> > > @cblichmann can probably answer this better than me but I assume that this is not something we want to pursue. Sandbox2 is not intended to give a full 'container' but rather run a single application in a tight sandbox. Running additional applications in the same sandbox requires a more relaxed policy and will reduce the overall effectiveness.
> 
> Precisely. We do not want to become a full container runtime. That space is already plenty crowded and has a lot of great solutions available. gVisor and Kata on the VM side and custom seccomp policies on the upstream Docker side. There are others as well.
> 
> > Do you have any public slides or videos explained in details for sandboxed-api/sandbox2 project?
> > I can only find "Developer Guide".
> 
> No, there are no public slides or videos. What content would you like to see a video for? Personally, I rarely find those useful. I do agree that our documentation can be improved a lot, but I think our time is better spend on creating tutorials/codelabs and background articles.

 If i want to support arm64, more introduction about high-level architecture and inner components is preferred.

**Comment by cblichmann** [comment]
> If i want to support arm64, more introduction about high-level architecture and inner components is preferred.

Does that mean you potentially want to contribute AArch64 support? :)

Adding a new processor architecture is actually not super-hard: The syscall definitions for the target arch need to be added in [sandbox2/syscall_defs.cc](https://github.com/google/sandboxed-api/blob/726cabe2f7ed41757b249d5f4a66dac3e4022dcf/sandboxed_api/sandbox2/syscall_defs.cc#L131). Then the `sandbox2::Syscall::CpuArch` enum needs to be extended and you'll need to update [sandbox2/regs.cc](https://github.com/google/sandboxed-api/blob/master/sandboxed_api/sandbox2/regs.cc) and the `RegisterValues` proto, adding a way to access syscall arguments.

That should get you 80-90% of the way already.

Of course, it'd also be great if you added QEMU-based integration tests that run on some CI infrastructure, additional tests, etc. ...

Taking it one step at a time this is totally manageable and we are certainly interested.

**Comment by cblichmann** [comment]
FYI arm64 ("AArch64") support has been functional since 19a8e38a511d2d540c4382cb09f0a15a648954a8 and 32-bit arm support is coming as well (see d0c8224e61efe31b63cdecac3dc0e1326f6b15dd).
