### ISSUE TITLE
Can't install library using cmake and make install

### ISSUE THREAD

**Issue by war-and-peace** [google/sandboxed-api#43]
My workspace configurations are the following: Kubuntu 20.04, GNU GCC 9.3, CMake 3.16.3.

I tried to build and install the library using CMake. For that I run the following commands:
```
cmake .
make
make install
```
The build was successful, but when I ran `make install` did nothing but printed the following:
![Screenshot_20200604_164104](https://user-images.githubusercontent.com/27621364/83764214-562d7380-a682-11ea-9700-63f485f0c2a1.png)

As far as I understand `make install` should've put header files and shared objects to `/usr/local` folder by default, isn't it right? If so, how can I fix this issue?

**Comment by cblichmann** [comment]
Hi there!

We do not support system-wide installation of Sandboxed API. We follow Google's live-at-head philosophy (similar to what Abseil does). Installing in a global sub-tree like `/usr/local` would mean that you can only ever have exactly one version of the library part of SAPI installed on any given system.

To add to that, Sandboxed API is a project that allows you to create sandboxes for other libraries, providing you with a sandboxed interface to program against. So it's not just a matter of installing SAPI somewhere.

I assume you want to embed SAPI in your own project? If so, take a look at the [`hello_sapi`](https://github.com/google/sandboxed-api/tree/master/sandboxed_api/examples/hello_sapi) example.
For embedding, you can use the contents of the `hello_sapi` folder as a starting point in your own project and set the `SAPI_ROOT` in the `CMakeLists.txt`.

**Comment by war-and-peace** [comment]
Hello! Yes, I want to embed SAPI in my project. The method you described works for me. Thanks!

**Comment by war-and-peace** [comment]
Well, honestly nothing fancy, nothing new). I am working on an online/offline programming contest creation and sharing tool (also unifying existing websites). I am planning to use sandboxing to execute submitted programs by users.

**Comment by cblichmann** [comment]
Nice! In this case you may also want to look into using Sandbox2 directly, see the [static](https://github.com/google/sandboxed-api/tree/master/sandboxed_api/sandbox2/examples/static) example. With a few adjustments, this also works for dynamically linked executables.

**Comment by war-and-peace** [comment]
Yes, I was also considering using sandbox2. Actually, this was in my head ever since sandboxing API was open-sourced, but did not have time to actually look into it. Thank you for the advice!
