### ISSUE TITLE
There has no curl submodule

### ISSUE THREAD

**Issue by xsmart** [google/sandboxed-api#70]
when follow the guide to build curl example, I find these has no curl submodule in oss-internship-2020/curl/curl_wrapper 
git submodule update --init --recursive

**Comment by cblichmann** [comment]
Hey there, thanks for reporting this issue. We'll likely move away from git submodules as they don't work well with our code publication process (internal repo -> Copybara code transforms -> GitHub).
The replacement will likely be using CMake's `FetchContent`.

Checking out a fresh copy of Curl into the `oss-internship-2020/curl/curl_wrapper/curl` directory should as least get you started, though.
