### ISSUE TITLE
Debian10 test can't work

### ISSUE THREAD

**Issue by xsmart** [google/sandboxed-api#71]
I can build on Debian 10 for libuv, but the example can't work
`user@debian10:~/sandbox/sandboxed-api/oss-internship-2020/libuv/build/examples$ ./helloworld 
[util.cc : 140] RAW: clone(): Operation not permitted [1]
[forkserver.cc : 496] RAW: Check pid != -1 failed: failed to fork initial namespaces process: Operation not permitted [1]
[fork_client.cc : 60] RAW: Receiving init PID from the ForkServer failed
E20210104 04:59:55.649554 32539 executor.cc:163] Could not obtain init PID
E20210104 04:59:55.650148 32536 helloworld.cc:85] HelloWorld failed: UNAVAILABLE: Could not start the sandbox
user@debian10:~/sandbox/sandboxed-api/oss-internship-2020/libuv/build/examples$ `

**Comment by happyCoder92** [comment]
Debian kernel has a patch that by default disables unprivileged user namespaces.

You will need:
```
echo 'kernel.unprivileged_userns_clone=1' | sudo tee /etc/sysctl.d/userns.conf
```
