### ISSUE TITLE
filewrapper: SIGABRT when trying to read from directory

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#89]
`filewrapper a b $'\n' s.h s.cc /dev` core dumps.  I expect a non-zero exit code and an error message, but no core dump.

**Comment by happyCoder92** [comment]
This is a build tool usually used through sapi_cc_embed_data rule and a directory input is unlikely in that scenario.
Indeed it will cause a CHECK failure, which depending on settings might result in coredump.
Any PRs improving error reporting of that tool are welcome.
